// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/personal-ide/DesktopWorkspace.tsx": () => import("../components/mockups/personal-ide/DesktopWorkspace.tsx"),
  "./components/mockups/personal-ide/MobileShell.tsx": () => import("../components/mockups/personal-ide/MobileShell.tsx")
};
