import { useState, useEffect, useRef, useCallback } from "react";
import { useGetProject, getGetProjectQueryKey, updateProject, useUpdateProject, Message } from "@workspace/api-client-react";
import { AxiomFlow } from "../AxiomFlow";
import type { ArchNode, NodeStateMap, HandoverSnapshot } from "../AxiomFlow";
import { SystemMap } from "../SystemMap";
import type { ArchNode as SystemMapNode } from "../SystemMap";

import { useThemeMode } from "@/lib/theme";
import { TheForge } from "../TheForge";
import { fileToBase64Safe } from "@/lib/image-resize";
import { reportError } from "../../lib/errorReporter";

const FLOW_NODE_TYPES = new Set<ArchNode["type"]>(["goal", "requirement", "blocker", "priority", "decision", "sprint", "wont"]);
const FLOW_NODE_META = new Set(["must", "should", "could", "wont"]);
const SYSTEM_NODE_IDS = new Set(["auth", "db", "api", "state", "ui", "logic"]);
const FLOW_MESSAGES_LIMIT = 50;

type FlowMessage = { role: "user" | "assistant"; content: string };

function toAsciiExportText(text: string): string {
  return text
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[╔╗╚╝]/g, "")
    .replace(/[═─]+/g, (divider) => "-".repeat(divider.length))
    .replace(/[▸▶]/g, "->")
    .replace(/[•●■◆]/g, "-")
    .replace(/[△▲]/g, "^")
    .replace(/[·]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[–—]/g, "-")
    .replace(/…/g, "...")
    .replace(/[^\x00-\x7F]/g, "");
}

function formatBlueprintForExport(bp: any): string {
  const c = bp.content ?? bp;
  const lines: string[] = [];
  lines.push("-".repeat(48));
  if (c.title)          lines.push(`  ${c.title.toUpperCase()}`);
  lines.push("-".repeat(48));
  lines.push("");
  if (c.idea)           lines.push(`THE IDEA\n${c.idea}`);
  if (c.opportunity)    lines.push(`\nOPPORTUNITY\n${c.opportunity}`);
  if (c.mechanism)      lines.push(`\nHOW IT WORKS\n${c.mechanism}`);
  if (c.landscape)      lines.push(`\nLANDSCAPE\n${c.landscape}`);
  if (c.risks?.length)  lines.push(`\nRISKS\n${c.risks.map((r: string) => `- ${r}`).join("\n")}`);
  if (c.openQuestions?.length) lines.push(`\nOPEN QUESTIONS\n${c.openQuestions.map((q: string) => `- ${q}`).join("\n")}`);
  if (c.nextSteps?.length) lines.push(`\nNEXT STEPS\n${c.nextSteps.map((s: string) => `- ${s}`).join("\n")}`);
  if (c.visualPrompt)   lines.push(`\nVISUAL DIRECTION\n${c.visualPrompt}`);
  lines.push("");
  lines.push("-".repeat(48));
  lines.push(`Generated by Axiom - ${new Date().toLocaleDateString()}`);
  return toAsciiExportText(lines.join("\n"));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function isFlowMessage(value: unknown): value is FlowMessage {
  return (
    isRecord(value) &&
    (value.role === "user" || value.role === "assistant") &&
    typeof value.content === "string"
  );
}

function flowMessagesStorageKey(projectId?: number): string | null {
  return typeof projectId === "number" ? `axiom-flow-messages-${projectId}` : null;
}

function loadFlowMessages(projectId?: number): FlowMessage[] {
  const storageKey = flowMessagesStorageKey(projectId);
  if (!storageKey || typeof window === "undefined") return [];

  try {
    const storedMessages = window.localStorage.getItem(storageKey);
    if (!storedMessages) return [];

    const parsedMessages: unknown = JSON.parse(storedMessages);
    if (!Array.isArray(parsedMessages)) return [];

    return parsedMessages.filter(isFlowMessage).slice(-FLOW_MESSAGES_LIMIT);
  } catch {
    return [];
  }
}

function saveFlowMessages(projectId: number | undefined, messages: FlowMessage[]): FlowMessage[] {
  const limitedMessages = messages.slice(-FLOW_MESSAGES_LIMIT);
  const storageKey = flowMessagesStorageKey(projectId);
  if (!storageKey || typeof window === "undefined") return limitedMessages;

  try {
    window.localStorage.setItem(storageKey, JSON.stringify(limitedMessages));
  } catch {
    // localStorage can be unavailable in privacy-restricted contexts.
  }

  return limitedMessages;
}

export function asFlowNodeType(value: unknown): ArchNode["type"] | null {
  return typeof value === "string" && FLOW_NODE_TYPES.has(value as ArchNode["type"])
    ? value as ArchNode["type"]
    : null;
}

export function asFlowMeta(value: unknown): ArchNode["meta"] | undefined {
  return typeof value === "string" && FLOW_NODE_META.has(value)
    ? value as ArchNode["meta"]
    : undefined;
}

export function flowNodeFallbackPosition(index: number): { x: number; y: number } {
  const angle = (2 * Math.PI * index) / 8 - Math.PI / 2;
  return {
    x: Math.round(300 + 160 * Math.cos(angle)),
    y: Math.round(250 + 160 * Math.sin(angle)),
  };
}

export function extractPersistedFlowNodes(nodeState: unknown): ArchNode[] {
  if (!isRecord(nodeState)) return [];
  return Object.entries(nodeState).flatMap(([id, raw], index): ArchNode[] => {
    if (SYSTEM_NODE_IDS.has(id) || !isRecord(raw)) return [];
    const label = typeof raw.label === "string" && raw.label.trim() ? raw.label.trim() : "";
    const type = asFlowNodeType(raw.type);
    if (!label || !type) return [];
    const fallback = flowNodeFallbackPosition(index);
    const strategicAnswer = typeof raw.strategicAnswer === "string" && raw.strategicAnswer.trim()
      ? raw.strategicAnswer.trim()
      : undefined;
    return [{
      id,
      label,
      type,
      resolved: Boolean(strategicAnswer) || raw.resolved === true,
      x: typeof raw.x === "number" ? raw.x : fallback.x,
      y: typeof raw.y === "number" ? raw.y : fallback.y,
      details: typeof raw.details === "string" && raw.details.trim() ? raw.details.trim() : undefined,
      meta: asFlowMeta(raw.meta),
      moscow: asFlowMeta(raw.moscow),
      question: typeof raw.question === "string" && raw.question.trim() ? raw.question.trim() : undefined,
      strategicAnswer,
    }];
  });
}


function orderNodesForStory(nodes: ArchNode[]): { goal: ArchNode | null; steps: ArchNode[] } {
  const goal = nodes.find(n => n.type === "goal") ?? null;
  const rest = nodes.filter(n => n.type !== "goal");
  const rank = (n: ArchNode): number => {
    const m = n.moscow ?? n.meta;
    if (n.type === "blocker") return 0;
    if (m === "must") return 1;
    if (n.type === "requirement") return 1;
    if (m === "should") return 2;
    if (n.type === "decision") return 3;
    if (m === "could") return 4;
    if (n.type === "sprint") return 5;
    if (m === "wont" || n.type === "wont") return 6;
    return 3;
  };
  const steps = [...rest].sort((a, b) => rank(a) - rank(b));
  return { goal, steps };
}


function detectPlatform(): string {
  const host = typeof window !== "undefined" ? window.location.hostname : "";
  if (host.includes("axiomsystem")) return "Axiom";
  if (host.includes("lovable")) return "LOVABLE";
  if (host.includes("replit") || host.includes("repl.co") || host.includes("replit.app")) return "REPLIT";
  if (host.includes("cursor")) return "CURSOR";
  if (host.includes("vercel")) return "VERCEL";
  if (host.includes("netlify")) return "NETLIFY";
  if (host.includes("localhost") || host.includes("127.0.0.1")) return "LOCAL";
  return "WEB";
}

function FlowCopyButton({ content }: { content: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      onClick={() => {
        navigator.clipboard.writeText(content).catch(() => {});
        setCopied(true);
        setTimeout(() => setCopied(false), 1600);
      }}
      title={copied ? "Copied!" : "Copy response"}
      aria-label="Copy response"
      style={{
        marginLeft: 4,
        display: "inline-flex",
        alignItems: "center",
        gap: 4,
        padding: "3px 7px",
        borderRadius: 6,
        background: "transparent",
        border: "1px solid rgba(var(--atlas-gold-rgb),0.18)",
        color: copied ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.75)",
        cursor: "pointer",
        fontFamily: "var(--app-font-mono)",
        fontSize: 9,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        transition: "color 160ms ease, border-color 160ms ease",
        WebkitTapHighlightColor: "transparent",
      }}
    >
      {copied ? (
        <svg width="10" height="10" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"><path d="M2 7l3 3 7-7" /></svg>
      ) : (
        <svg width="10" height="10" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="5" y="5" width="8" height="8" rx="1.5" /><path d="M9 5V3a1 1 0 00-1-1H3a1 1 0 00-1 1v5a1 1 0 001 1h2" /></svg>
      )}
      <span>{copied ? "Copied" : "Copy"}</span>
    </button>
  );
}

export function FlowPanel({ projectId, onHomeNav, onSendIntent, onFillIntent, onBackToChat, onNavLedger, onNavPreview, onMapReadinessChange, displayedReadinessScore, onSystemNodeMessage, onHandover, handoverPending, lastHandoverHash, resolvedNodeIds, onResolvedConsumed, onSnapshotChange, handoverOpen, onHandoverOpenChange, isMobile, onOpenForge, externalForgeNodes, onForgeNodesConsumed, onForgeCompleted, entryCount, activeCatch }: { projectId?: number; onHomeNav: () => void; onSendIntent?: (text: string) => void; onFillIntent?: (text: string) => void; onBackToChat?: () => void; onNavLedger?: () => void; onNavPreview?: () => void; onMapReadinessChange?: (score: number) => void; displayedReadinessScore?: number; onSystemNodeMessage?: (text: string) => void; onHandover?: (payload: { snapshot: HandoverSnapshot; title: string }) => void; handoverPending?: boolean; lastHandoverHash?: string | null; resolvedNodeIds?: string[]; onResolvedConsumed?: () => void; onSnapshotChange?: (s: HandoverSnapshot | null) => void; handoverOpen?: boolean; onHandoverOpenChange?: (open: boolean) => void; isMobile?: boolean; onOpenForge?: () => void; externalForgeNodes?: ArchNode[]; onForgeNodesConsumed?: () => void; onForgeCompleted?: () => void; entryCount?: number; activeCatch?: boolean }) {
  const [readinessScore, setReadinessScore] = useState(0);
  useEffect(() => { onMapReadinessChange?.(readinessScore); }, [readinessScore, onMapReadinessChange]);

  // Consume nodes pushed from the external Forge button into the canvas
  useEffect(() => {
    if (externalForgeNodes && externalForgeNodes.length > 0) {
      setPendingNodes(externalForgeNodes);
      onForgeNodesConsumed?.();
    }
  }, [externalForgeNodes, onForgeNodesConsumed]);
  const [nodes, setNodes] = useState<ArchNode[]>([]);
  const [pendingNodes, setPendingNodes] = useState<ArchNode[]>([]);
  const [lensView, setLensView] = useState<"designer" | "builder" | "storyteller">("designer");
  const [showChat, setShowChat] = useState(true);
  const [showQuickPrompt, setShowQuickPrompt] = useState(false);
  const [signals, setSignals] = useState<string[]>([""]);
  const [activeSignalIdx, setActiveSignalIdx] = useState(0);
  const [signalAdded, setSignalAdded] = useState(false);
  const [sentFlash, setSentFlash] = useState(false);
  const sentFlashTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const intent = signals[activeSignalIdx] ?? "";
  const setIntent = (val: string) => setSignals(prev => prev.map((s, i) => i === activeSignalIdx ? val : s));

  const [flowChatTab, setFlowChatTab] = useState<"flow" | "intent">("flow");
  const [flowMessages, setFlowMessages] = useState<FlowMessage[]>(() => loadFlowMessages(projectId));
  const [flowAttachedFiles, setFlowAttachedFiles] = useState<File[]>([]);
  const flowFileInputRef = useRef<HTMLInputElement>(null);
  const [chatFullscreen, setChatFullscreen] = useState(false);
  const [flowLoading, setFlowLoading] = useState(false);
  const [flowInput, setFlowInput] = useState("");
  const flowScrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => () => { if (sentFlashTimerRef.current) clearTimeout(sentFlashTimerRef.current); }, []);

  useEffect(() => {
    setFlowMessages(loadFlowMessages(projectId));
  }, [projectId]);

  const addFlowMessage = useCallback((message: FlowMessage) => {
    setFlowMessages(prev => saveFlowMessages(projectId, [...prev, message]));
  }, [projectId]);

  useEffect(() => {
    if (flowScrollRef.current) {
      flowScrollRef.current.scrollTop = flowScrollRef.current.scrollHeight;
    }
  }, [flowMessages, flowLoading]);

  const sendFlowMessage = useCallback(async (text: string) => {
    if (!text.trim() || flowLoading) return;
    const files = flowAttachedFiles;
    setFlowAttachedFiles([]);
    const imageFile = files.find(f => f.type.startsWith("image/"));
    const otherFiles = files.filter(f => f !== imageFile);
    const suffix = otherFiles.length > 0 ? `\n[Attached: ${otherFiles.map(f => f.name).join(", ")}]` : "";
    const fullText = text + suffix;
    addFlowMessage({ role: "user", content: fullText });
    setFlowInput("");
    setFlowLoading(true);
    try {
      const nodeContext = nodes.length > 0
        ? `Current canvas nodes:\n${nodes.map(n => `- [${n.type}] ${n.label}${n.strategicAnswer ? " (answered)" : " (unanswered)"}`).join("\n")}`
        : "Canvas is empty — no nodes yet.";
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          projectId,
          message: fullText,
          flowMode: true,
          flowNodes: nodes,
          history: flowMessages.map(m => ({ role: m.role, content: m.content })),
          projectMap: nodeContext,
          mode: "plan",
          ...(imageFile ? await fileToBase64Safe(imageFile).then(r => ({ imageBase64: r.base64, imageMediaType: r.mediaType })).catch(() => ({ imageBase64: "", imageMediaType: "" })) : {}),
        }),
      }).then(async (r) => {
        if (!r.ok) return Promise.reject(r.status);
        const contentType = r.headers.get("content-type") ?? "";
        if (!contentType.includes("text/event-stream")) {
          return r.json();
        }
        const reader = r.body!.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        let finalPayload: any = null;
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          const blocks = buffer.split("\n\n");
          buffer = blocks.pop() ?? "";
          for (const block of blocks) {
            let evtName = "";
            let evtData = "";
            for (const line of block.split("\n")) {
              if (line.startsWith("event: ")) evtName = line.slice(7).trim();
              else if (line.startsWith("data: ")) evtData = line.slice(6);
            }
            if (!evtData) continue;
            if (evtName === "done") {
              try { finalPayload = JSON.parse(evtData); } catch {}
            }
          }
        }
        return finalPayload;
      });
      const incoming = (res.flowNodes ?? []) as ArchNode[];
      addFlowMessage({ role: "assistant", content: res.content ?? "" });
      if (incoming.length > 0) setPendingNodes(incoming);
    } catch (error) {
      void reportError(error, { projectId });
      addFlowMessage({ role: "assistant", content: "Something went wrong. Try again." });
    } finally {
      setFlowLoading(false);
    }
  }, [addFlowMessage, flowMessages, flowAttachedFiles, flowLoading, nodes, projectId]);

  const handleSend = useCallback(() => {
    if (!intent.trim()) return;
    onSendIntent?.(intent.trim());
    setSignals(prev => prev.map((s, i) => i === activeSignalIdx ? "" : s));
    setSentFlash(true);
    if (sentFlashTimerRef.current) clearTimeout(sentFlashTimerRef.current);
    sentFlashTimerRef.current = setTimeout(() => setSentFlash(false), 1400);
  }, [intent, onSendIntent, activeSignalIdx]);

  const addSignal = () => {
    setSignals(prev => [...prev, ""]);
    setActiveSignalIdx(signals.length);
    setSignalAdded(true);
    setTimeout(() => setSignalAdded(false), 1200);
  };

  const deleteActiveSignal = () => {
    if (signals.length <= 1) return;
    setSignals(prev => prev.filter((_, i) => i !== activeSignalIdx));
    setActiveSignalIdx(i => Math.max(0, i - 1));
  };
  const platform = detectPlatform();
  const themeMode = useThemeMode();
  const { data: activeProject } = useGetProject(projectId ?? 0, {
    query: { enabled: !!projectId, queryKey: getGetProjectQueryKey(projectId ?? 0) },
  });
  const activeProjectName = activeProject?.name;
  const updateProject = useUpdateProject();
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const nodeStateRef = useRef<Record<string, unknown>>({});
  const nodeStateSeededRef = useRef(false);

  useEffect(() => {
    nodeStateSeededRef.current = false;
    nodeStateRef.current = {};
  }, [projectId]);

  useEffect(() => {
    if (nodeStateSeededRef.current) return;
    const persisted = activeProject?.nodeState as Record<string, unknown> | null | undefined;
    if (persisted && typeof persisted === "object") {
      nodeStateRef.current = { ...persisted };
      nodeStateSeededRef.current = true;
    }
  }, [activeProject?.nodeState]);

  const handleNodesChange = useCallback((updatedNodes: ArchNode[]) => {
    setNodes(updatedNodes);
    if (!projectId) return;
    // New shape: per-node object with display metadata plus resolution state.
    // The DB column is jsonb so this is non-breaking; AxiomFlow's hydration
    // handler still tolerates the legacy boolean shape on read.
    const axiomState: Record<string, {
      resolved: boolean;
      strategicAnswer?: string;
      label: string;
      type: ArchNode["type"];
      x: number;
      y: number;
      details?: string;
      meta?: ArchNode["meta"];
      moscow?: ArchNode["moscow"];
      question?: string;
    }> = {};
    updatedNodes.forEach(n => {
      axiomState[n.id] = {
        resolved: n.resolved,
        ...(n.strategicAnswer ? { strategicAnswer: n.strategicAnswer } : {}),
        label: n.label,
        type: n.type,
        x: n.x,
        y: n.y,
        ...(n.details ? { details: n.details } : {}),
        ...(n.meta ? { meta: n.meta } : {}),
        ...(n.moscow ? { moscow: n.moscow } : {}),
        ...(n.question ? { question: n.question } : {}),
      };
    });
    nodeStateRef.current = { ...nodeStateRef.current, ...axiomState };
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    saveTimerRef.current = setTimeout(() => {
      updateProject.mutate({ id: projectId, data: { nodeState: { ...nodeStateRef.current } } });
    }, 1000);
  }, [projectId, updateProject]);

  // Save architecture layer node state (SystemMap nodes: auth/db/api/state/ui/logic)
  // Merges with AxiomFlow's node state since both write to the same project.nodeState field
  const archSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (archSaveTimerRef.current) clearTimeout(archSaveTimerRef.current); }, []);

  const handleArchNodesChange = useCallback((updatedArchNodes: SystemMapNode[]) => {
    if (!projectId) return;
    const archState: Record<string, boolean> = {};
    updatedArchNodes.forEach(n => { archState[n.id] = n.resolved; });
    nodeStateRef.current = { ...nodeStateRef.current, ...archState };
    if (archSaveTimerRef.current) clearTimeout(archSaveTimerRef.current);
    archSaveTimerRef.current = setTimeout(() => {
      updateProject.mutate({ id: projectId, data: { nodeState: { ...nodeStateRef.current } } });
    }, 1000);
  }, [projectId, updateProject]);

  // Export Blueprint — copy / download the current map
  const [exportFlash, setExportFlash] = useState<null | "copied" | "downloaded">(null);
  const buildBlueprintExport = useCallback((): any => {
    const score = displayedReadinessScore ?? readinessScore;
    return {
      content: {
        title: "Axiom Blueprint",
        idea: `Readiness: ${score}%`,
        landscape: nodes.map(n => `- ${n.label} [${n.type}${n.meta ? `/${n.meta}` : ""}]: ${n.resolved ? "Resolved" : "Unresolved"}`).join("\n"),
      },
    };
  }, [nodes, displayedReadinessScore, readinessScore]);
  const handleExportCopy = useCallback(async () => {
    const blueprint = buildBlueprintExport();
    const text = formatBlueprintForExport(blueprint);
    try { await navigator.clipboard.writeText(text); }
    catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
    setExportFlash("copied");
    setTimeout(() => setExportFlash(null), 1600);
  }, [buildBlueprintExport]);
  const handleExportDownload = useCallback(() => {
    const blueprint = buildBlueprintExport();
    const text = formatBlueprintForExport(blueprint);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(blueprint.content?.title ?? blueprint.title ?? "blueprint").toLowerCase().replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExportFlash("downloaded");
    setTimeout(() => setExportFlash(null), 1600);
  }, [buildBlueprintExport]);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", overflow: "hidden", paddingBottom: 64 }}>
      <div style={{
        height: 1, flexShrink: 0,
        background: "linear-gradient(to right, transparent 0%, rgba(var(--atlas-gold-rgb),0.18) 20%, rgba(var(--atlas-gold-rgb),0.38) 50%, rgba(var(--atlas-gold-rgb),0.18) 80%, transparent 100%)",
      }} />

      {/* Map area — Axiom Flow (strategic) + System Map (architecture readiness)
          When intent capture is visible, cap at 54% so the input section always
          has enough room on every phone size. */}
      <div style={{ position: "relative", flex: chatFullscreen ? "0 0 0" : showChat ? "0 0 auto" : 1, height: chatFullscreen ? 0 : showChat ? "min(54%, calc(100% - 316px))" : undefined, minHeight: chatFullscreen ? 0 : showChat ? 200 : 0, overflow: "hidden", display: "flex", flexDirection: "column", transition: "flex 350ms ease" }}>
        {/* Map header — Show both toggle + Export icons (replaces the old bottom toggle bar) */}
        <div style={{
          position: "absolute", top: 8, right: 8, zIndex: 12,
          display: "flex", gap: 4, alignItems: "center",
          background: "rgba(var(--atlas-bg-rgb),0.72)",
          backdropFilter: "blur(6px)",
          border: "1px solid rgba(var(--atlas-gold-rgb),0.18)",
          borderRadius: 8, padding: 3,
        }}>
          <button
            onClick={() => { setChatFullscreen(false); setShowChat(v => !v); }}
            title={showChat ? "Map fullscreen" : "Show both (map + intent)"}
            aria-label={showChat ? "Map fullscreen" : "Show split view"}
            style={{
              minWidth: 28, height: 24, padding: "0 6px", borderRadius: 5,
              background: "transparent", border: "none", cursor: "pointer",
              color: "rgba(var(--atlas-gold-rgb),0.78)",
              display: "flex", alignItems: "center", justifyContent: "center",
            }}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              {showChat ? (
                <>
                  <path d="M4 4h7v7H4z" />
                  <path d="M13 13h7v7h-7z" />
                </>
              ) : (
                <>
                  <rect x="3" y="3" width="18" height="18" rx="2" />
                  <line x1="3" y1="12" x2="21" y2="12" />
                </>
              )}
            </svg>
          </button>
          <span style={{ width: 1, height: 14, background: "rgba(var(--atlas-gold-rgb),0.18)" }} aria-hidden />
          <button
            onClick={handleExportCopy}
            title="Copy blueprint to clipboard"
            aria-label="Copy blueprint"
            style={{
              minWidth: 28, height: 24, padding: "0 6px", borderRadius: 5,
              background: exportFlash === "copied" ? "rgba(var(--atlas-gold-rgb),0.18)" : "transparent",
              border: "none", cursor: "pointer",
              color: "rgba(var(--atlas-gold-rgb),0.78)",
              display: "flex", alignItems: "center", justifyContent: "center",
            }}
          >
            {exportFlash === "copied" ? (
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
            ) : (
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
            )}
          </button>
          <button
            onClick={handleExportDownload}
            title="Download blueprint as TXT"
            aria-label="Download blueprint"
            style={{
              minWidth: 28, height: 24, padding: "0 6px", borderRadius: 5,
              background: exportFlash === "downloaded" ? "rgba(var(--atlas-gold-rgb),0.18)" : "transparent",
              border: "none", cursor: "pointer",
              color: "rgba(var(--atlas-gold-rgb),0.78)",
              display: "flex", alignItems: "center", justifyContent: "center",
            }}
          >
            {exportFlash === "downloaded" ? (
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
            ) : (
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
            )}
          </button>
        </div>
        {/* Axiom Flow canvas */}
        <div style={{ flex: 1, minHeight: 0, position: "relative", overflow: "hidden" }}>
          <div
            style={{
              position: "absolute",
              bottom: 8,
              right: 10,
              zIndex: 14,
              display: "flex",
              gap: 2,
              padding: 2,
              background: "rgba(var(--atlas-bg-rgb),0.78)",
              backdropFilter: "blur(14px) saturate(140%)",
              border: "1px solid rgba(var(--atlas-gold-rgb),0.18)",
              borderRadius: 999,
              boxShadow: "0 4px 16px rgba(0,0,0,0.18)",
            }}
          >
            {(["designer", "builder", "storyteller"] as const).map((lens) => {
              const active = lensView === lens;
              const label =
                lens === "designer" ? "Designer" : lens === "builder" ? "Builder" : "Storyteller";
              return (
                <button
                  key={lens}
                  type="button"
                  onClick={() => setLensView(lens)}
                  style={{
                    padding: "3px 9px",
                    borderRadius: 999,
                    border: "none",
                    cursor: "pointer",
                    background: active ? "rgba(var(--atlas-gold-rgb),0.16)" : "transparent",
                    color: active ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.6)",
                    fontFamily: "var(--app-font-mono)",
                    fontSize: 8,
                    fontWeight: 700,
                    letterSpacing: "0.1em",
                    textTransform: "uppercase",
                    transition: "all 160ms ease",
                  }}
                >
                  {label}
                </button>
              );
            })}
          </div>
          {/* Empty map nudge — show Forge prompt when canvas has no nodes yet */}
          {nodes.length === 0 && onOpenForge && (
            <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 10, pointerEvents: "none" }}>
              <button
                onClick={onOpenForge}
                aria-label="Open Forge"
                style={{
                  pointerEvents: "auto", display: "flex", flexDirection: "column" as const, alignItems: "center", gap: 6,
                  padding: "14px 20px", borderRadius: 12, cursor: "pointer",
                  background: "rgba(var(--atlas-gold-rgb),0.06)",
                  border: "1px dashed rgba(var(--atlas-gold-rgb),0.3)",
                  color: "rgba(var(--atlas-gold-rgb),0.6)",
                  backdropFilter: "blur(4px)",
                  transition: "all 200ms ease",
                }}
              >
                <svg width={18} height={18} viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.8 }}>
                  <path d="M9 2L3 8.5l2.5 2.5L12 4.5 9 2z" />
                  <path d="M5.5 11L2 14.5" />
                  <path d="M11 3.5L13 5.5" />
                </svg>
                <span style={{ fontFamily: "var(--app-font-mono)", fontSize: 9, letterSpacing: "0.12em", textTransform: "uppercase" as const }}>
                  Forge — populate from a transcript
                </span>
              </button>
            </div>
          )}
          {lensView === "designer" && (
            <AxiomFlow
              projectId={projectId}
              onReadinessChange={setReadinessScore}
              onNodesChange={handleNodesChange}
              compact
              onBackToChat={onBackToChat}
              detectedBuilder={platform.toLowerCase()}
              onNodeFocus={(text) => setIntent(text)}
              initialNodeState={(activeProject?.nodeState as NodeStateMap | null) ?? null}
              pendingNodes={pendingNodes}
              onPendingConsumed={() => setPendingNodes([])}
              onUnansweredQuestionOpen={({ mirror }) => onSystemNodeMessage?.(mirror)}
              onHandover={onHandover}
              handoverPending={handoverPending}
              lastHandoverHash={lastHandoverHash}
              onSnapshotChange={onSnapshotChange}
              handoverOpen={handoverOpen}
              onHandoverOpenChange={onHandoverOpenChange}
              isMobile={isMobile}
              projectName={activeProjectName}
            />
          )}
          {lensView === "builder" && (
            <div style={{ position: "absolute", inset: 0, overflowY: "auto", padding: "20px 18px 28px" }}>
              {(() => {
                const goal = nodes.find(n => n.type === "goal") ?? null;
                const rest = nodes.filter(n => n.type !== "goal");
                if (!goal && rest.length === 0) {
                  return <div style={{ display: "flex", height: "100%", alignItems: "center", justifyContent: "center", color: "rgba(var(--atlas-muted-rgb),0.5)", fontFamily: "var(--app-font-mono)", fontSize: 11, letterSpacing: "0.08em", textAlign: "center", padding: "0 24px" }}>Nothing to build yet — define nodes with Atlas and they'll appear here as schema.</div>;
                }
                const typeLabel = (t: ArchNode["type"]) => {
                  if (t === "requirement") return "requirements";
                  if (t === "decision") return "decisions";
                  if (t === "sprint") return "sprints";
                  if (t === "blocker") return "blockers";
                  if (t === "priority") return "priorities";
                  if (t === "wont") return "out_of_scope";
                  return String(t);
                };
                const order: ArchNode["type"][] = ["requirement", "decision", "sprint", "priority", "blocker", "wont"];
                const grouped = order
                  .map(t => ({ type: t, name: typeLabel(t), items: rest.filter(n => n.type === t) }))
                  .filter(g => g.items.length > 0);
                const fieldType = (n: ArchNode): string => {
                  const m = n.moscow ?? n.meta;
                  if (n.type === "blocker") return "blocker";
                  if (n.type === "decision") return n.resolved ? "decision" : "decision · open";
                  if (m === "must") return "must";
                  if (m === "should") return "should";
                  if (m === "could") return "could";
                  if (m === "wont" || n.type === "wont") return "won't";
                  if (n.type === "sprint") return "sprint";
                  return n.resolved ? "defined" : "open";
                };
                const trim = (s: string, n = 28) => s.length > n ? s.slice(0, n - 1) + "…" : s;
                return (
                  <>
                    <div style={{ fontFamily: "var(--app-font-mono)", fontSize: 9, letterSpacing: "0.22em", textTransform: "uppercase", color: "rgba(var(--atlas-gold-rgb),0.55)", marginBottom: 14 }}>
                      // schema · v0.1
                    </div>
                    {goal && (
                      <div style={{
                        fontFamily: "var(--app-font-mono)",
                        fontSize: 11,
                        color: "var(--atlas-gold)",
                        border: "1px dashed rgba(var(--atlas-gold-rgb),0.35)",
                        borderRadius: 8,
                        padding: "10px 14px",
                        textAlign: "center" as const,
                        marginBottom: 18,
                        background: "rgba(var(--atlas-gold-rgb),0.03)",
                      }}>
                        // seed: {trim(goal.label, 64)}
                      </div>
                    )}
                    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 10, marginBottom: 14 }}>
                      {grouped.map(g => (
                        <div key={g.type} style={{
                          border: "1px solid rgba(var(--atlas-gold-rgb),0.18)",
                          borderRadius: 6,
                          background: "rgba(255,255,255,0.015)",
                          overflow: "hidden",
                        }}>
                          <div style={{
                            fontFamily: "var(--app-font-mono)",
                            fontSize: 10,
                            letterSpacing: "0.14em",
                            color: "var(--atlas-gold)",
                            padding: "8px 10px",
                            borderBottom: "1px solid rgba(var(--atlas-gold-rgb),0.18)",
                            background: "rgba(var(--atlas-gold-rgb),0.05)",
                          }}>
                            {g.name}
                          </div>
                          {g.items.map((n, i) => (
                            <div key={n.id} style={{
                              fontFamily: "var(--app-font-mono)",
                              fontSize: 10.5,
                              color: "rgba(var(--atlas-muted-rgb),0.85)",
                              padding: "6px 10px",
                              borderBottom: i < g.items.length - 1 ? "1px solid rgba(var(--atlas-gold-rgb),0.08)" : "none",
                              display: "flex",
                              gap: 8,
                              alignItems: "baseline",
                            }}>
                              <span style={{ flex: 1, minWidth: 0, color: "var(--atlas-fg)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{trim(n.label)}</span>
                              <span style={{ color: "rgba(var(--atlas-muted-rgb),0.6)" }}>: {fieldType(n)}</span>
                            </div>
                          ))}
                        </div>
                      ))}
                    </div>
                    {goal && grouped.length > 0 && (
                      <p style={{
                        fontFamily: "var(--app-font-mono)",
                        fontSize: 10,
                        color: "rgb(95,169,161)",
                        letterSpacing: "0.14em",
                        textAlign: "center" as const,
                        margin: 0,
                      }}>
                        ↳ join on goal_id
                      </p>
                    )}
                  </>
                );
              })()}
            </div>
          )}
          {lensView === "storyteller" && (
            <div style={{ position: "absolute", inset: 0, overflowY: "auto", padding: "20px 22px 28px" }}>
              {(() => {
                const { goal, steps } = orderNodesForStory(nodes);
                if (!goal && steps.length === 0) {
                  return <div style={{ display: "flex", height: "100%", alignItems: "center", justifyContent: "center", color: "rgba(var(--atlas-muted-rgb),0.5)", fontFamily: "var(--app-font-mono)", fontSize: 11, letterSpacing: "0.08em" }}>Nothing mapped yet — talk to Atlas to build the story.</div>;
                }
                return (
                  <>
                    <div style={{ fontFamily: "var(--app-font-mono)", fontSize: 9, letterSpacing: "0.22em", textTransform: "uppercase", color: "rgba(var(--atlas-gold-rgb),0.55)", marginBottom: 10 }}>
                      // the arc
                    </div>
                    <div style={{ fontSize: 26, fontWeight: 500, lineHeight: 1.2, color: "var(--atlas-fg)", marginBottom: 24, fontFamily: "var(--app-font-serif, Georgia, serif)" }}>
                      {goal ? goal.label : "Untitled"}
                    </div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
                      {steps.map((n, i) => {
                        const m = n.moscow ?? n.meta;
                        const isBlocker = n.type === "blocker";
                        const isDecision = n.type === "decision";
                        const accent = isBlocker ? "var(--atlas-ember, rgba(239,120,80,0.9))"
                          : isDecision ? "rgba(230,130,80,0.9)"
                          : "rgba(var(--atlas-gold-rgb),0.7)";
                        return (
                          <div key={n.id} style={{ display: "flex", gap: 14, alignItems: "flex-start", padding: "12px 0", borderBottom: "1px solid rgba(var(--atlas-gold-rgb),0.06)" }}>
                            <div style={{ flexShrink: 0, width: 26, height: 26, borderRadius: "50%", border: `1px solid ${accent}`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--app-font-mono)", fontSize: 10, color: accent }}>
                              {i + 1}
                            </div>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ fontSize: 16, lineHeight: 1.4, color: "var(--atlas-fg)", fontFamily: "var(--app-font-serif, Georgia, serif)" }}>
                                {n.label}
                              </div>
                              {(m || isBlocker || isDecision) && (
                                <div style={{ marginTop: 3, fontFamily: "var(--app-font-mono)", fontSize: 8, letterSpacing: "0.12em", textTransform: "uppercase", color: accent, opacity: 0.8 }}>
                                  {isBlocker ? "blocker" : isDecision ? "open decision" : m}
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </>
                );
              })()}
            </div>
          )}
        </div>
        {/* System Map — architecture layer readiness (auth/db/api/state/ui/logic)
            Hidden on mobile: its readiness score feeds the workspace header ring,
            and stacking two full canvases in the mobile overlay is confusing.
            Desktop keeps both views so the two layers remain visible at once. */}
        {!isMobile && (
          <div style={{
            flexShrink: 0, height: 180, position: "relative", overflow: "hidden",
            borderTop: "1px solid rgba(var(--atlas-gold-rgb),0.12)",
          }}>
            <SystemMap
              projectId={projectId}
              compact
              detectedBuilder={platform.toLowerCase()}
              onNodesChange={handleArchNodesChange}
              initialNodeState={(activeProject?.nodeState as NodeStateMap | null) ?? null}
              resolvedNodeIds={resolvedNodeIds}
              onResolvedConsumed={onResolvedConsumed}
            />
          </div>
        )}
      </div>

      {/* Slim toggle — chat fullscreen only (Show both moved to map header) */}
      {showChat && (
        <div style={{
          display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "4px 12px",
          background: "var(--atlas-flow-pane-bg)",
          borderTop: "1px solid rgba(var(--atlas-gold-rgb),0.08)",
          flexShrink: 0,
        }}>
          <span style={{
            color: "rgba(var(--atlas-gold-rgb),0.35)", fontSize: 10,
            fontFamily: "var(--app-font-mono)", letterSpacing: "0.05em",
            userSelect: "none",
          }}>
            {chatFullscreen ? "flow chat" : "intent capture"}
          </span>
          <button
            onClick={() => setChatFullscreen(v => !v)}
            style={{
              background: chatFullscreen ? "rgba(var(--atlas-gold-rgb),0.14)" : "rgba(var(--atlas-gold-rgb),0.07)",
              border: `1px solid ${chatFullscreen ? "rgba(var(--atlas-gold-rgb),0.5)" : "rgba(var(--atlas-gold-rgb),0.28)"}`,
              borderRadius: 5, padding: "2px 9px", cursor: "pointer",
              color: "rgba(var(--atlas-gold-rgb),0.78)", fontSize: 9,
              fontFamily: "var(--app-font-mono)", letterSpacing: "0.05em",
            }}>
            {chatFullscreen ? "⊠ Show map" : "⛶ Chat full"}
          </button>
        </div>
      )}


      {/* INTENT CAPTURE */}
      {showChat && (
        <div style={{ flex: 1, minHeight: 190, overflow: "hidden", display: "flex", flexDirection: "column", background: "var(--atlas-flow-pane-bg)" }}>
          <style>{`@keyframes intent-dot-pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(.85)}}`}</style>

          {/* Tab switcher — FLOW CHAT | INTENT */}
          <div style={{ display: "flex", alignItems: "center", gap: 0, padding: "5px 14px 4px", flexShrink: 0, borderBottom: "1px solid rgba(var(--atlas-gold-rgb),0.08)" }}>
            <button
              onClick={() => setFlowChatTab("flow")}
              style={{
                background: flowChatTab === "flow" ? "rgba(var(--atlas-gold-rgb),0.12)" : "transparent",
                border: "none", borderBottom: flowChatTab === "flow" ? "2px solid rgba(var(--atlas-gold-rgb),0.7)" : "2px solid transparent",
                padding: "3px 10px 4px", cursor: "pointer",
                color: flowChatTab === "flow" ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.55)",
                fontSize: 9, fontWeight: 700, letterSpacing: "0.12em",
                fontFamily: "var(--app-font-mono)", textTransform: "uppercase",
                transition: "all 180ms ease",
              }}
            >⬡ Flow Chat</button>
            <button
              onClick={() => setFlowChatTab("intent")}
              style={{
                background: flowChatTab === "intent" ? "rgba(var(--atlas-gold-rgb),0.12)" : "transparent",
                border: "none", borderBottom: flowChatTab === "intent" ? "2px solid rgba(var(--atlas-gold-rgb),0.7)" : "2px solid transparent",
                padding: "3px 10px 4px", cursor: "pointer",
                color: flowChatTab === "intent" ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.55)",
                fontSize: 9, fontWeight: 700, letterSpacing: "0.12em",
                fontFamily: "var(--app-font-mono)", textTransform: "uppercase",
                transition: "all 180ms ease",
              }}
            >Intent</button>
          </div>

          {/* FLOW CHAT — Atlas drives the canvas */}
          {flowChatTab === "flow" && (
            <div style={{ flex: 1, minHeight: 0, overflow: "hidden", display: "flex", flexDirection: "column", padding: "0 14px 10px" }}>
              {/* Message list */}
              <div
                ref={flowScrollRef}
                style={{
                  flex: 1, minHeight: 0, overflowY: "auto",
                  padding: "8px 0 4px",
                  display: "flex", flexDirection: "column", gap: 8,
                }}
              >
                {flowMessages.length === 0 && (
                  <div style={{
                    display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
                    height: "100%", gap: 6, opacity: 0.45,
                  }}>
                    <span style={{ fontSize: 18 }}>⬡</span>
                    <span style={{ fontSize: 10, color: "rgba(var(--atlas-muted-rgb),0.8)", fontFamily: "var(--app-font-mono)", letterSpacing: "0.08em", textAlign: "center", lineHeight: 1.5 }}>
                      Talk to Atlas.<br />Nodes appear on the canvas as you plan.
                    </span>
                  </div>
                )}
                {flowMessages.map((m, i) => (
                  <div key={i} style={{
                    alignSelf: m.role === "user" ? "flex-end" : "flex-start",
                    maxWidth: "86%",
                    display: "flex", flexDirection: "column",
                    alignItems: m.role === "user" ? "flex-end" : "flex-start",
                    gap: 4,
                  }}>
                    <div style={{
                      background: m.role === "user"
                        ? "rgba(var(--atlas-gold-rgb),0.12)"
                        : "var(--atlas-surface)",
                      border: m.role === "user"
                        ? "1px solid rgba(var(--atlas-gold-rgb),0.28)"
                        : "1px solid rgba(var(--atlas-gold-rgb),0.10)",
                      borderRadius: m.role === "user" ? "10px 10px 2px 10px" : "10px 10px 10px 2px",
                      padding: "7px 10px",
                      fontSize: 12, lineHeight: 1.55,
                      color: m.role === "user" ? "#E7E5E4" : "var(--atlas-fg)",
                      fontFamily: "inherit",
                      whiteSpace: "pre-wrap", wordBreak: "break-word",
                    }}>
                      {m.content}
                    </div>
                    {m.role === "assistant" && m.content.trim().length > 0 && (
                      <FlowCopyButton content={m.content} />
                    )}
                  </div>
                ))}
                {flowLoading && (
                  <div style={{
                    alignSelf: "flex-start",
                    background: "var(--atlas-surface)",
                    border: "1px solid rgba(var(--atlas-gold-rgb),0.10)",
                    borderRadius: "10px 10px 10px 2px",
                    padding: "8px 12px",
                    display: "flex", gap: 4, alignItems: "center",
                  }}>
                    {[0, 1, 2].map(d => (
                      <div key={d} style={{
                        width: 5, height: 5, borderRadius: "50%",
                        background: "rgba(var(--atlas-gold-rgb),0.6)",
                        animation: `intent-dot-pulse 1.2s ease-in-out ${d * 0.2}s infinite`,
                      }} />
                    ))}
                  </div>
                )}
              </div>

              {/* Hidden file input for Flow Chat */}
              <input
                ref={flowFileInputRef}
                type="file"
                multiple
                accept="image/jpeg,image/png,image/gif,image/webp,application/pdf,.txt,.md,.csv,.json,.js,.ts,.tsx,.jsx"
                style={{ display: "none" }}
                onChange={(e) => {
                  const incoming = Array.from(e.target.files ?? []).slice(0, 10);
                  setFlowAttachedFiles(prev => [...prev, ...incoming].slice(0, 10));
                  e.target.value = "";
                }}
              />

              {/* Flow Chat attachment preview strip */}
              {flowAttachedFiles.length > 0 && (
                <div style={{ display: "flex", gap: 5, marginBottom: 6, overflowX: "auto", paddingBottom: 2, flexShrink: 0 }}>
                  {flowAttachedFiles.map((file, idx) => (
                    <div key={idx} style={{ position: "relative", flexShrink: 0 }}>
                      {file.type.startsWith("image/") ? (
                        <img src={URL.createObjectURL(file)} alt={file.name} style={{ width: 46, height: 46, borderRadius: 6, objectFit: "cover", border: "1px solid rgba(var(--atlas-gold-rgb),0.25)", display: "block" }} />
                      ) : (
                        <div style={{ width: 46, height: 46, borderRadius: 6, background: "rgba(var(--atlas-gold-rgb),0.07)", border: "1px solid rgba(var(--atlas-gold-rgb),0.2)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 2, overflow: "hidden" }}>
                          <svg width="13" height="13" viewBox="0 0 16 16" fill="none"><path d="M13 7.5l-5.5 5.5a4 4 0 01-5.66-5.66l6-6a2.5 2.5 0 013.54 3.54l-6 6a1 1 0 01-1.42-1.42l5.5-5.5" stroke="rgba(var(--atlas-gold-rgb),0.6)" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" /></svg>
                          <span style={{ fontSize: 7, color: "rgba(var(--atlas-gold-rgb),0.55)", maxWidth: 40, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontFamily: "var(--app-font-mono)" }}>{file.name.split(".").pop()?.toUpperCase() ?? "FILE"}</span>
                        </div>
                      )}
                      <button onClick={() => setFlowAttachedFiles(prev => prev.filter((_, i) => i !== idx))} aria-label="Remove attachment" style={{ position: "absolute", top: -4, right: -4, minWidth: 44, minHeight: 44, borderRadius: "50%", background: "var(--atlas-bg)", border: "1px solid rgba(var(--atlas-gold-rgb),0.3)", cursor: "pointer", color: "var(--atlas-fg)", fontSize: 9, lineHeight: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: 14, zIndex: 1 }}>×</button>
                    </div>
                  ))}
                </div>
              )}

              {/* Input row */}
              <div style={{
                display: "flex", gap: 6, alignItems: "flex-end",
                paddingTop: 6, borderTop: "1px solid rgba(var(--atlas-gold-rgb),0.07)",
                flexShrink: 0,
              }}>
                {/* Paperclip button */}
                <button
                  onClick={() => flowFileInputRef.current?.click()}
                  title="Attach file"
                  aria-label="Attach file"
                  style={{
                    minWidth: 44, minHeight: 44, padding: 8, flexShrink: 0, borderRadius: 7,
                    background: "transparent", border: "none",
                    color: flowAttachedFiles.length > 0 ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.4)",
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center",
                    transition: "color 160ms ease",
                  }}
                  onMouseEnter={e => (e.currentTarget.style.color = "var(--atlas-gold)")}
                  onMouseLeave={e => { if (!flowAttachedFiles.length) e.currentTarget.style.color = "rgba(var(--atlas-muted-rgb),0.4)"; }}
                >
                  <svg width="13" height="13" viewBox="0 0 16 16" fill="none"><path d="M13 7.5l-5.5 5.5a4 4 0 01-5.66-5.66l6-6a2.5 2.5 0 013.54 3.54l-6 6a1 1 0 01-1.42-1.42l5.5-5.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" /></svg>
                </button>
                <textarea
                  value={flowInput}
                  onChange={e => setFlowInput(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendFlowMessage(flowInput); }
                  }}
                  placeholder="What are you building? Atlas will map it..."
                  rows={2}
                  disabled={flowLoading}
                  style={{
                    flex: 1, resize: "none", background: "var(--atlas-surface)",
                    border: "1px solid rgba(var(--atlas-gold-rgb),0.20)", borderRadius: 8,
                    padding: "7px 10px", color: "var(--atlas-fg)", fontSize: 12,
                    lineHeight: 1.5, fontFamily: "inherit", outline: "none",
                    opacity: flowLoading ? 0.6 : 1,
                  }}
                />
                <button
                  onClick={() => sendFlowMessage(flowInput)}
                  disabled={!flowInput.trim() || flowLoading}
                  aria-label="Send message"
                  style={{
                    minWidth: 44, minHeight: 44, padding: 6, flexShrink: 0, borderRadius: 8,
                    background: flowInput.trim() && !flowLoading ? "rgba(var(--atlas-gold-rgb),0.18)" : "transparent",
                    border: `1px solid ${flowInput.trim() && !flowLoading ? "rgba(var(--atlas-gold-rgb),0.45)" : "rgba(var(--atlas-muted-rgb),0.2)"}`,
                    cursor: flowInput.trim() && !flowLoading ? "pointer" : "not-allowed",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    color: flowInput.trim() && !flowLoading ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.3)",
                    transition: "all 180ms ease",
                  }}
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M2 21l21-9L2 3v7l15 2-15 2v7z" />
                  </svg>
                </button>
              </div>
            </div>
          )}

          {/* Intent capture — prompt card */}
          {flowChatTab === "intent" && (
          <div style={{ flex: 1, minHeight: 0, overflow: "hidden", padding: "0 14px 12px" }}>
            <div style={{
              height: "100%", display: "flex", flexDirection: "column",
              background: "rgba(var(--atlas-surface-rgb),0.92)",
              border: "1px solid rgba(var(--atlas-gold-rgb),0.16)",
              borderRadius: 12, overflow: "hidden",
            }}>
              {/* Card header — platform badge + signal selector + add button, all in one row */}
              <div style={{
                display: "flex", alignItems: "center", gap: 6,
                padding: "7px 10px 6px",
                borderBottom: "1px solid rgba(var(--atlas-gold-rgb),0.07)",
                flexShrink: 0,
              }}>
                {/* Platform badge — translucent pill, color keyed to detected system */}
                {(() => {
                  const p = platform.toLowerCase();
                  const isReplit  = p === "replit";
                  const isCursor  = p === "cursor";
                  const isLovable = p === "lovable";
                  const isParchment = themeMode === "parchment";
                  const color  = isReplit  ? (isParchment ? "oklch(0.42 0.16 150)" : "oklch(0.74 0.18 150)")
                               : isCursor  ? (isParchment ? "oklch(0.42 0.16 240)" : "oklch(0.74 0.18 240)")
                               : isLovable ? (isParchment ? "oklch(0.42 0.18 300)" : "oklch(0.74 0.20 300)")
                               : "rgba(var(--atlas-gold-rgb),0.78)";
                  const bg     = isReplit  ? (isParchment ? "oklch(0.88 0.08 150 / 55%)" : "oklch(0.28 0.12 150 / 28%)")
                               : isCursor  ? (isParchment ? "oklch(0.88 0.08 240 / 55%)" : "oklch(0.28 0.12 240 / 28%)")
                               : isLovable ? (isParchment ? "oklch(0.88 0.10 300 / 55%)" : "oklch(0.28 0.12 300 / 28%)")
                               : "rgba(var(--atlas-gold-rgb),0.10)";
                  const border = isReplit  ? (isParchment ? "oklch(0.50 0.16 150 / 60%)" : "oklch(0.55 0.18 150 / 50%)")
                               : isCursor  ? (isParchment ? "oklch(0.50 0.16 240 / 60%)" : "oklch(0.55 0.18 240 / 50%)")
                               : isLovable ? (isParchment ? "oklch(0.50 0.18 300 / 60%)" : "oklch(0.55 0.20 300 / 50%)")
                               : "rgba(var(--atlas-gold-rgb),0.30)";
                  return (
                    <span style={{
                      fontSize: 9, fontWeight: 700, color,
                      background: bg, border: `1px solid ${border}`,
                      borderRadius: 999, padding: "2px 9px",
                      letterSpacing: "0.10em", textTransform: "uppercase",
                      flexShrink: 0, fontFamily: "var(--app-font-mono)",
                    }}>
                      {platform}
                    </span>
                  );
                })()}
                {/* Signal selector — inline, takes remaining space */}
                <select
                  value={activeSignalIdx}
                  onChange={e => setActiveSignalIdx(Number(e.target.value))}
                  style={{
                    flex: 1, minWidth: 0, background: "transparent",
                    border: "1px solid rgba(var(--atlas-gold-rgb),0.13)",
                    borderRadius: 5, padding: "3px 6px",
                    color: "rgba(var(--atlas-gold-rgb),0.65)", fontSize: 9.5,
                    fontFamily: "var(--app-font-mono)", cursor: "pointer",
                  }}>
                  {signals.map((s, i) => (
                    <option key={i} value={i}>Signal #{i + 1}{s.trim() ? ` — ${s.trim().slice(0, 22)}${s.trim().length > 22 ? "…" : ""}` : ""}</option>
                  ))}
                </select>
                {/* Delete signal — only shown when multiple signals exist */}
                {signals.length > 1 && (
                  <button
                    onClick={deleteActiveSignal}
                    title="Delete this signal"
                    aria-label="Delete signal"
                    style={{
                      minWidth: 44, minHeight: 44, padding: 12, borderRadius: 4, flexShrink: 0,
                      background: "rgba(239,68,68,0.08)", border: "1px solid rgba(239,68,68,0.25)",
                      color: "rgba(239,68,68,0.6)", cursor: "pointer",
                      display: "flex", alignItems: "center", justifyContent: "center",
                      fontSize: 12, lineHeight: 1,
                    }}
                  >×</button>
                )}
                {/* Add signal */}
                <button
                  onClick={addSignal}
                  style={{
                    background: signalAdded ? "rgba(var(--atlas-gold-rgb),0.22)" : "rgba(var(--atlas-gold-rgb),0.09)",
                    border: `1px solid ${signalAdded ? "rgba(var(--atlas-gold-rgb),0.7)" : "rgba(var(--atlas-gold-rgb),0.3)"}`,
                    borderRadius: 6, padding: "3px 9px", cursor: "pointer", flexShrink: 0,
                    color: "var(--atlas-gold)", fontSize: 9.5, fontWeight: 700, letterSpacing: "0.04em",
                    fontFamily: "var(--app-font-mono)", transition: "all 300ms",
                  }}>
                  {signalAdded ? "✓" : "+ Signal"}
                </button>
              </div>

              {/* Textarea — minHeight:0 ensures it shrinks on small viewports/keyboard-up */}
              <textarea
                value={intent}
                onChange={e => setIntent(e.target.value)}
                placeholder="Describe what you want to build or change — e.g. 'Add login with Google to my Express app using passport.js'"
                onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); } }}
                style={{
                  flex: 1, minHeight: 0, overflowY: "auto",
                  background: "transparent", border: "none", outline: "none",
                  resize: "none", padding: "12px 14px",
                  color: "var(--atlas-fg)", fontSize: 13, lineHeight: 1.6,
                  fontFamily: "inherit",
                }}
              />

              {/* Card footer */}
              <div style={{
                display: "flex", alignItems: "center", justifyContent: "space-between",
                padding: "7px 14px",
                borderTop: "1px solid rgba(var(--atlas-gold-rgb),0.05)",
                flexShrink: 0,
              }}>
                <button style={{ background: "none", border: "none", cursor: "pointer", color: "rgba(var(--atlas-muted-rgb),0.45)", padding: 4 }}>
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l9.19-9.19a4 4 0 015.66 5.66l-9.2 9.19a2 2 0 01-2.83-2.83l8.49-8.48" />
                  </svg>
                </button>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <button style={{ background: "none", border: "none", cursor: "pointer", color: "rgba(var(--atlas-muted-rgb),0.45)", padding: 4 }}>
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/>
                    </svg>
                  </button>
                  <button
                    onClick={handleSend}
                    style={{
                      width: 30, height: 30, borderRadius: 8,
                      background: sentFlash ? "rgba(var(--atlas-gold-rgb),0.28)" : intent.trim() ? "rgba(var(--atlas-gold-rgb),0.14)" : "transparent",
                      border: `1px solid ${sentFlash ? "rgba(var(--atlas-gold-rgb),0.7)" : intent.trim() ? "rgba(var(--atlas-gold-rgb),0.38)" : "rgba(var(--atlas-muted-rgb),0.22)"}`,
                      cursor: "pointer",
                      display: "flex", alignItems: "center", justifyContent: "center",
                      color: sentFlash ? "var(--atlas-gold)" : intent.trim() ? "var(--atlas-gold)" : "rgba(var(--atlas-muted-rgb),0.32)",
                      transition: "all 200ms",
                      fontSize: sentFlash ? 13 : undefined,
                      fontWeight: sentFlash ? 700 : undefined,
                    }}
                  >
                    {sentFlash ? "✓" : (
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M2 21l21-9L2 3v7l15 2-15 2v7z" />
                      </svg>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>
          )}
        </div>
      )}

      {/* Quick Prompt sheet */}
      {showQuickPrompt && (
        <TheForge
          platform={platform}
          readinessScore={readinessScore}
          activeProjectName={activeProjectName}
          projectId={projectId}
          onClose={() => setShowQuickPrompt(false)}
          onNodesReady={(nodes) => { setPendingNodes(nodes); onForgeCompleted?.(); setShowQuickPrompt(false); }}
          onFillChatInput={onFillIntent}
        />
      )}

      {/* Dock owned by parent workspace — do not render a second one here
          (caused the stacked mobile footer when Flow tab was active). */}

    </div>
  );
}
