import { and, desc, eq, isNotNull } from "drizzle-orm";
import { db, connectionsTable, projectsTable } from "@workspace/db";
import { decryptToken } from "./tokenCrypto";

const GH_API = "https://api.github.com";

function ghHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "Axiom-Atlas/1.0",
    "Content-Type": "application/json",
  };
}

export async function getGithubTokenForUser(userId: number): Promise<string | null> {
  const [conn] = await db
    .select({ token: connectionsTable.token })
    .from(connectionsTable)
    .where(and(
      eq(connectionsTable.userId, userId),
      eq(connectionsTable.type, "github"),
      isNotNull(connectionsTable.token),
    ))
    .orderBy(desc(connectionsTable.createdAt))
    .limit(1);

  if (conn?.token) {
    const plain = decryptToken(conn.token);
    if (plain && plain !== "__server__") return plain;
  }

  const [proj] = await db
    .select({ githubToken: projectsTable.githubToken })
    .from(projectsTable)
    .where(and(eq(projectsTable.userId, userId), isNotNull(projectsTable.githubToken)))
    .orderBy(desc(projectsTable.createdAt))
    .limit(1);

  if (proj?.githubToken) {
    const plain = decryptToken(proj.githubToken);
    if (plain && plain !== "__server__") return plain;
  }

  return null;
}

export function sanitizeRepoName(name: string): string {
  const clean = name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100);
  return clean || "new-project";
}

type ScaffoldFile = { path: string; content: string };

export type ProjectBrief = {
  purpose?: string | null;
  audience?: string | null;
  wedge?: string | null;
  openQuestions?: string[] | null;
};

export type ProjectMemory = {
  projectName: string;
  genome: {
    purpose?: string | null;
    audience?: string | null;
    wedge?: string | null;
    stage?: string | null;
    stack?: string[];
    protectedAreas?: string[];
    constraints?: string[];
    openQuestions?: string[];
  };
  recentSessions?: Array<{ title: string; status: string }>;
  recentEntries?: Array<{ title: string; mode?: string | null }>;
};

export function generateAtlasMd(memory: ProjectMemory): string {
  const { projectName, genome = {}, recentSessions = [], recentEntries = [] } = memory;
  const title = projectName
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  const generatedAt = new Date().toISOString();
  const sourceParts = ["genome"];
  if (recentEntries.length > 0) sourceParts.push(`${recentEntries.length} ledger entr${recentEntries.length === 1 ? "y" : "ies"}`);
  if (recentSessions.length > 0) sourceParts.push(`${recentSessions.length} session${recentSessions.length === 1 ? "" : "s"}`);

  const purpose = genome.purpose?.trim() || null;
  const audience = genome.audience?.trim() || null;
  const wedge = genome.wedge?.trim() || null;
  const stage = genome.stage?.trim() || null;
  const stack = (genome.stack ?? []).filter(Boolean);
  const protectedAreas = (genome.protectedAreas ?? []).filter(Boolean);
  const constraints = (genome.constraints ?? []).filter(Boolean);
  const openQuestions = (genome.openQuestions ?? []).filter((q): q is string => !!q?.trim());

  const lines: string[] = [
    `<!-- Generated by Axiom Atlas — do not edit manually.`,
    `     Project: ${title}`,
    `     Generated: ${generatedAt}`,
    `     Sources: ${sourceParts.join(", ")} -->`,
    "",
    `# Atlas Operating Context — ${title}`,
    "",
    "## North Star",
    "",
    purpose ?? "*Not yet defined. Set purpose in project settings.*",
    "",
    "## Audience",
    "",
    audience ?? "*Not yet defined.*",
    "",
    "## Wedge",
    "",
    wedge ?? "*Not yet defined.*",
    "",
  ];

  if (stage) lines.push("## Current Stage", "", stage, "");

  if (stack.length > 0) {
    lines.push("## Architecture", "");
    stack.forEach(s => lines.push(`- ${s}`));
    lines.push("");
  } else {
    lines.push("## Architecture", "", "*Not yet defined — add stack via project settings.*", "");
  }

  if (protectedAreas.length > 0) {
    lines.push("## Protected Areas", "");
    protectedAreas.forEach(a => lines.push(`- ${a}`));
    lines.push("");
  } else {
    lines.push("## Protected Areas", "", "*Not yet defined.*", "");
  }

  if (constraints.length > 0) {
    lines.push("## Do Not Change", "");
    constraints.forEach(c => lines.push(`- ${c}`));
    lines.push("");
  } else {
    lines.push("## Do Not Change", "", "*Not yet defined.*", "");
  }

  if (recentSessions.length > 0) {
    lines.push("## Active Sessions", "");
    recentSessions.forEach(s => {
      const tag = s.status !== "active" ? ` *(${s.status})*` : "";
      lines.push(`- ${s.title}${tag}`);
    });
    lines.push("");
  }

  if (recentEntries.length > 0) {
    lines.push(
      "## Recent Ledger Context",
      "",
      "<!-- Most recent committed entries — use as session context for what has been decided or built -->",
    );
    recentEntries.slice(0, 15).forEach(e => {
      const tag = e.mode ? ` *(${e.mode})*` : "";
      lines.push(`- ${e.title}${tag}`);
    });
    lines.push("");
  }

  if (openQuestions.length > 0) {
    lines.push("## Open Questions", "");
    openQuestions.forEach(q => lines.push(`- ${q}`));
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "*Auto-generated by Axiom Atlas. Do not edit manually — Refresh Atlas Memory to update.*",
  );

  return lines.join("\n") + "\n";
}

export function getScaffoldFiles(appName: string, opts: {
  projectBrief?: ProjectBrief;
  isCodeProject?: boolean;
  projectMemory?: ProjectMemory;
} = {}): ScaffoldFile[] {
  const { projectBrief, isCodeProject = true, projectMemory } = opts;
  const title = appName
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  const today = new Date().toISOString().slice(0, 10);
  const purpose = projectBrief?.purpose?.trim() || null;
  const audience = projectBrief?.audience?.trim() || null;
  const wedge = projectBrief?.wedge?.trim() || null;
  const openQuestions = (projectBrief?.openQuestions ?? []).filter((q): q is string => !!q?.trim());

  // ── README.md ─────────────────────────────────────────────────────────────
  const readmeLines: string[] = [
    `# ${title}`,
    "",
    `> Created with [Axiom](https://axiomsystem.app) — a strategic thinking partner.`,
    "",
  ];
  if (purpose) readmeLines.push("## What this is", "", purpose, "");
  if (isCodeProject) {
    readmeLines.push(
      "## Getting started",
      "",
      "```bash",
      "npm install",
      "npm run dev",
      "```",
      "",
    );
  }
  readmeLines.push(
    "## Project context",
    "",
    "See [PROJECT.md](./PROJECT.md) for the full project brief and [docs/roadmap.md](./docs/roadmap.md) for direction.",
  );

  // ── PROJECT.md ────────────────────────────────────────────────────────────
  const projectLines: string[] = [
    `# ${title} — Project Brief`,
    "",
    `> This file is maintained by Axiom Atlas. Update it as the project evolves.`,
    "",
    "## Purpose",
    "",
    purpose ?? "*Not yet defined.*",
    "",
    "## Audience",
    "",
    audience ?? "*Not yet defined.*",
    "",
    "## Wedge",
    "",
    wedge ?? "*Not yet defined.*",
    "",
    "## Open questions",
    "",
  ];
  if (openQuestions.length > 0) {
    openQuestions.forEach(q => projectLines.push(`- ${q}`));
    projectLines.push("");
  } else {
    projectLines.push("*None recorded yet.*", "");
  }
  projectLines.push("---", "", `*Activated on ${today} via Axiom Atlas.*`);

  // ── docs/decisions.md ─────────────────────────────────────────────────────
  const decisionsContent = [
    "# Decision Log",
    "",
    `> Decisions made during the life of **${title}**, tracked for context and accountability.`,
    "",
    "---",
    "",
    `## ${today} — Project initialized`,
    "",
    "**Decision:** Created and activated this project via Axiom Atlas.",
    "**Rationale:** Initial activation — no prior decisions recorded.",
    "**Status:** Committed",
  ].join("\n") + "\n";

  // ── docs/roadmap.md ───────────────────────────────────────────────────────
  const roadmapLines: string[] = [
    "# Roadmap",
    "",
    `> High-level direction and milestones for **${title}**.`,
    "",
    "---",
    "",
    "## Phase 1 — Foundation",
    "",
    "- [ ] Define purpose and audience",
    "- [ ] Identify the wedge",
  ];
  if (openQuestions.length > 0) {
    openQuestions.forEach(q => roadmapLines.push(`- [ ] ${q}`));
  } else {
    roadmapLines.push("- [ ] Start the first working session");
  }
  roadmapLines.push("", "## Backlog", "", "*Add items here as the project evolves.*");

  // ── Base files (every Atlas-created repo gets these) ──────────────────────
  const files: ScaffoldFile[] = [
    { path: "README.md", content: readmeLines.join("\n") + "\n" },
    { path: "PROJECT.md", content: projectLines.join("\n") + "\n" },
    {
      path: ".gitignore",
      content: isCodeProject
        ? "node_modules\ndist\n.env\n.env.local\n.DS_Store\n*.tsbuildinfo\n"
        : ".DS_Store\n.env\n.env.local\n",
    },
    { path: "docs/decisions.md", content: decisionsContent },
    { path: "docs/roadmap.md", content: roadmapLines.join("\n") + "\n" },
    { path: "ATLAS.md", content: generateAtlasMd(projectMemory ?? { projectName: appName, genome: {} }) },
  ];

  // ── Code scaffold (build/app projects only) ───────────────────────────────
  if (isCodeProject) {
    files.push(
      {
        path: "index.html",
        content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
      },
      {
        path: "package.json",
        content: JSON.stringify({
          name: sanitizeRepoName(appName),
          private: true,
          version: "0.0.0",
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc && vite build",
            preview: "vite preview",
          },
          dependencies: {
            react: "^18.3.1",
            "react-dom": "^18.3.1",
          },
          devDependencies: {
            "@types/react": "^18.3.1",
            "@types/react-dom": "^18.3.1",
            "@vitejs/plugin-react": "^4.3.2",
            autoprefixer: "^10.4.20",
            postcss: "^8.4.47",
            tailwindcss: "^3.4.14",
            typescript: "^5.5.3",
            vite: "^5.4.8",
          },
        }, null, 2),
      },
      {
        path: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: {
            target: "ES2020",
            useDefineForClassFields: true,
            lib: ["ES2020", "DOM", "DOM.Iterable"],
            module: "ESNext",
            skipLibCheck: true,
            moduleResolution: "bundler",
            allowImportingTsExtensions: true,
            isolatedModules: true,
            noEmit: true,
            jsx: "react-jsx",
            strict: true,
          },
          include: ["src"],
        }, null, 2),
      },
      {
        path: "vite.config.ts",
        content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
      },
      {
        path: "tailwind.config.js",
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
      },
      {
        path: "postcss.config.js",
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,
      },
      {
        path: "src/index.css",
        content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
      },
      {
        path: "src/main.tsx",
        content: `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`,
      },
      {
        path: "src/App.tsx",
        content: `export default function App() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex items-center justify-center p-8">
      <div className="text-center space-y-4 max-w-lg">
        <h1 className="text-4xl font-bold tracking-tight">${title}</h1>
        <p className="text-gray-400 text-lg">
          Your project is ready. Start building with Atlas.
        </p>
      </div>
    </div>
  )
}
`,
      },
    );
  }

  return files;
}

export type BootstrapResult =
  | { ok: true; linkedRepo: string; htmlUrl: string; repoName: string; previewUrl: string; existingRepoLinked?: boolean; autoScaffolded?: boolean }
  | { ok: false; error: string; noToken?: boolean };

export async function bootstrapGitHubRepo(opts: {
  token: string;
  projectId: number;
  projectName: string;
  projectBrief?: ProjectBrief;
  isCodeProject?: boolean;
  projectMemory?: ProjectMemory;
}): Promise<BootstrapResult> {
  const { token, projectId, projectName } = opts;

  // 1. Get authenticated GitHub user login
  const meResp = await fetch(`${GH_API}/user`, { headers: ghHeaders(token) });
  if (!meResp.ok) {
    return { ok: false, error: `GitHub auth failed (${meResp.status})` };
  }
  const meData = await meResp.json() as { login: string };
  const repoName = sanitizeRepoName(projectName);

  // 2. Proactive existence check — avoid a wasted create+422 round-trip.
  //    GET the repo by name first; only create if it doesn't exist.
  let repoData: { full_name: string; html_url: string; pushed_at: string | null; size: number };
  let existingRepoLinked = false;
  let existingRepoIsEmpty = false;

  const existingCheck = await fetch(
    `${GH_API}/repos/${meData.login}/${repoName}`,
    { headers: ghHeaders(token) }
  );

  if (existingCheck.ok) {
    // Repo already exists under this account — link it.
    // If it has never been pushed to (pushed_at === null, size === 0) we will
    // still scaffold it below so the user never needs to tap "Hydrate" manually.
    repoData = await existingCheck.json() as { full_name: string; html_url: string; pushed_at: string | null; size: number };
    existingRepoLinked = true;
    existingRepoIsEmpty = !repoData.pushed_at || repoData.size === 0;
  } else {
    // Repo doesn't exist — create it
    const createResp = await fetch(`${GH_API}/user/repos`, {
      method: "POST",
      headers: ghHeaders(token),
      body: JSON.stringify({
        name: repoName,
        description: opts.projectBrief?.purpose
          ? opts.projectBrief.purpose.slice(0, 255)
          : "Built with Axiom Atlas",
        private: true,
        auto_init: false,
      }),
    });

    if (!createResp.ok) {
      const errBody = await createResp.json() as { message?: string; errors?: Array<{ message?: string }> };
      const msg = errBody.errors?.[0]?.message ?? errBody.message ?? "Unknown error";
      return { ok: false, error: `Failed to create repo: ${msg}` };
    }

    repoData = await createResp.json() as { full_name: string; html_url: string; pushed_at: string | null; size: number };
  }
  const fullName = repoData.full_name;

  // 3. Create blobs for each scaffold file
  // 3–7. Scaffold+commit when creating a brand-new repo OR when linking an
  // existing repo that has never had any pushes (empty repo). If the existing
  // repo has content (pushed_at is set, size > 0) we skip scaffolding to
  // preserve whatever the user already has there.
  if (!existingRepoLinked || existingRepoIsEmpty) {
    const files = getScaffoldFiles(repoName, {
      projectBrief: opts.projectBrief,
      isCodeProject: opts.isCodeProject,
      projectMemory: opts.projectMemory,
    });
    const commitMessage = opts.isCodeProject === false
      ? "Initial Atlas scaffold — docs project"
      : "Initial Atlas scaffold — app project";

    if (!existingRepoLinked) {
      // Atlas just created this repo via the API — git backend is initialized,
      // Git Data API works. Use blobs → tree → commit → ref for a single clean commit.
      const blobResults = await Promise.all(
        files.map(async (f) => {
          const r = await fetch(`${GH_API}/repos/${fullName}/git/blobs`, {
            method: "POST",
            headers: ghHeaders(token),
            body: JSON.stringify({ content: f.content, encoding: "utf-8" }),
          });
          if (!r.ok) throw new Error(`Blob creation failed for ${f.path}`);
          const b = await r.json() as { sha: string };
          return { path: f.path, sha: b.sha, mode: "100644" as const, type: "blob" as const };
        }),
      );

      const treeResp = await fetch(`${GH_API}/repos/${fullName}/git/trees`, {
        method: "POST",
        headers: ghHeaders(token),
        body: JSON.stringify({ tree: blobResults }),
      });
      if (!treeResp.ok) return { ok: false, error: "Failed to create git tree" };
      const treeData = await treeResp.json() as { sha: string };

      const commitResp = await fetch(`${GH_API}/repos/${fullName}/git/commits`, {
        method: "POST",
        headers: ghHeaders(token),
        body: JSON.stringify({ message: commitMessage, tree: treeData.sha, parents: [] }),
      });
      if (!commitResp.ok) return { ok: false, error: "Failed to create initial commit" };
      const commitData = await commitResp.json() as { sha: string };

      const refResp = await fetch(`${GH_API}/repos/${fullName}/git/refs`, {
        method: "POST",
        headers: ghHeaders(token),
        body: JSON.stringify({ ref: "refs/heads/main", sha: commitData.sha }),
      });
      if (!refResp.ok) return { ok: false, error: "Failed to set main branch" };

      await fetch(`${GH_API}/repos/${fullName}`, {
        method: "PATCH",
        headers: ghHeaders(token),
        body: JSON.stringify({ default_branch: "main" }),
      });
    } else {
      // User linked an existing empty repo — its git state is unknown.
      // GitHub's Git Data API returns 409 "Git Repository is empty" on repos
      // that have never had a commit regardless of how they were created.
      // The Contents API is the only endpoint guaranteed to work in this state:
      // it initializes the git backend and creates the default branch automatically.
      for (const f of files) {
        const putResp = await fetch(`${GH_API}/repos/${fullName}/contents/${f.path}`, {
          method: "PUT",
          headers: ghHeaders(token),
          body: JSON.stringify({
            message: commitMessage,
            content: Buffer.from(f.content, "utf-8").toString("base64"),
            branch: "main",
          }),
        });
        // Ignore 422 (file already exists from a previous partial scaffold attempt)
        if (!putResp.ok) {
          const errText = await putResp.text();
          if (!errText.includes("already exists") && !errText.includes("sha")) {
            return { ok: false, error: `Failed to scaffold ${f.path}: ${errText}` };
          }
        }
      }

      // Set default branch to main after the Contents API has created it
      await fetch(`${GH_API}/repos/${fullName}`, {
        method: "PATCH",
        headers: ghHeaders(token),
        body: JSON.stringify({ default_branch: "main" }),
      });
    }
  }

  // 8. Link the repo + set StackBlitz preview URL on the project
  const stackblitzUrl = `https://stackblitz.com/github/${fullName}`;
  await db
    .update(projectsTable)
    .set({ linkedRepo: fullName, previewUrl: stackblitzUrl })
    .where(eq(projectsTable.id, projectId));

  return { ok: true, linkedRepo: fullName, htmlUrl: repoData.html_url, repoName, previewUrl: stackblitzUrl, existingRepoLinked, autoScaffolded: existingRepoLinked && existingRepoIsEmpty };
}
