#!/bin/bash
set -e

echo "[build-frontend] Building frontend..."
pnpm --filter @workspace/atlas-frontend run build

echo "[build-frontend] Removing API server source maps..."
find artifacts/api-server/dist -name "*.map" -delete 2>/dev/null || true

echo "[build-frontend] Removing large packages that are no longer needed at runtime..."

# Frontend-only packages (bundled into dist/public/ by Vite — not needed at runtime)
rm -rf node_modules/.pnpm/react-icons*/
rm -rf node_modules/.pnpm/lucide-react*/
rm -rf node_modules/.pnpm/three*/
rm -rf node_modules/.pnpm/pdfjs-dist*/
rm -rf node_modules/.pnpm/date-fns*/
rm -rf node_modules/.pnpm/jspdf*/
rm -rf node_modules/.pnpm/html2pdf.js*/
rm -rf node_modules/.pnpm/web-streams-polyfill*/
rm -rf node_modules/.pnpm/core-js*/
rm -rf node_modules/.pnpm/@shikijs*/

# Test tools (never needed at runtime)
rm -rf node_modules/.pnpm/playwright*/
rm -rf node_modules/.pnpm/@playwright*/
rm -rf node_modules/.pnpm/chromium-bidi*/
rm -rf node_modules/.pnpm/vitest*/
rm -rf node_modules/.pnpm/@testing-library*/
rm -rf node_modules/.pnpm/jsdom*/

# Build tools (builds are complete — safe to remove)
rm -rf node_modules/.pnpm/typescript*/
rm -rf node_modules/.pnpm/esbuild*/
rm -rf node_modules/.pnpm/drizzle-kit*/
rm -rf node_modules/.pnpm/vite*/
rm -rf node_modules/.pnpm/@vitejs*/
rm -rf node_modules/.pnpm/tailwindcss*/
rm -rf node_modules/.pnpm/@tailwindcss*/
rm -rf node_modules/.pnpm/lightningcss*/
rm -rf node_modules/.pnpm/prettier*/

echo "[build-frontend] node_modules size after cleanup: $(du -sh node_modules | cut -f1)"

echo "[build-frontend] Pruning pnpm store..."
# The pnpm content-addressable store lives inside the workspace at
# .local/share/pnpm/store/v10 and is included in the deployment image.
# It grows throughout dev sessions as new package versions are installed.
# All builds are complete at this point so the store is no longer needed.
PNPM_STORE="$(pnpm store path 2>/dev/null || echo '')"
if [ -n "$PNPM_STORE" ] && [ -d "$PNPM_STORE" ]; then
  echo "[build-frontend] Removing pnpm store at $PNPM_STORE..."
  rm -rf "$PNPM_STORE"
  echo "[build-frontend] pnpm store removed."
else
  echo "[build-frontend] pnpm store not found, skipping."
fi

echo "[build-frontend] Removing git history (not needed at runtime)..."
# .git is ~1 GB and grows with every checkpoint. The running server
# (node artifacts/api-server/dist/index.mjs) and static frontend
# have no dependency on version history at runtime.
rm -rf .git

echo "[build-frontend] Removing agent workspace files (not needed at runtime)..."
# .local contains agent skills (~1.3 GB of markdown/scripts) used only
# during development. They are not referenced by the production server.
rm -rf .local

echo "[build-frontend] Removing build cache..."
# .cache accumulates Vite/esbuild/turbo cache entries throughout dev sessions.
# All builds are complete — safe to remove.
rm -rf .cache

echo "[build-frontend] Removing attached_assets (agent screenshots, not needed at runtime)..."
# attached_assets contains screenshots taken by the dev agent (~700 MB+).
# Not referenced by the production server or frontend.
rm -rf attached_assets

echo "[build-frontend] Removing other dev-only workspace directories..."
rm -rf .agents        # agent memory files
rm -rf .project-workspaces  # dev workspace state
rm -rf docs handoffs supabase local .lovable .upm

echo "[build-frontend] Writing production API launcher..."
# Capture the ACTUAL node binary via process.execPath (not the wrapper script).
# process.execPath returns the real ELF binary that runs in this process.
# The Replit RTLD loader resolves its library dependencies at runtime even if
# the production nix store uses different hashes — the same mechanism the
# -wrapped script uses, but we replicate it in portable /bin/sh below.
ACTUAL_NODE=$(node -e "process.stdout.write(process.execPath)" 2>/dev/null || echo "")
WRAPPER_NODE=$(command -v node 2>/dev/null || echo "")
echo "[build-frontend] Actual node (process.execPath): ${ACTUAL_NODE:-not found}"
echo "[build-frontend] Wrapper node (which): ${WRAPPER_NODE:-not found}"

# Read the RTLD loader path from the wrapper so we can replicate it
RTLD_LOADER_PATH=$(grep 'LD_AUDIT' "$WRAPPER_NODE" 2>/dev/null | grep -o '/nix/store/[^"]*' | head -1 || echo "")
echo "[build-frontend] RTLD loader: ${RTLD_LOADER_PATH:-not found}"

cat > run-api.sh << LAUNCHER_EOF
#!/bin/sh
# Production API server launcher — generated by build-frontend-prod.sh at build time.
# See run-api.sh in the repo for documentation on why this approach is used.

ENTRY="artifacts/api-server/dist/index.mjs"

# Replicate Replit's node wrapper: set up RTLD library path resolution.
# This allows the node binary to resolve its nix-store library deps even when
# the production nix store has different hashes than the dev environment.
if [ -n "\${REPLIT_LD_LIBRARY_PATH-}" ]; then
  if [ "\${REPLIT_RTLD_LOADER:-}" = "1" ] && [ "\${REPLIT_NIX_CHANNEL:-}" != "legacy" ]; then
    export LD_AUDIT="${RTLD_LOADER_PATH:-/nix/store/sj11ljhx4n79h9g0167f8lg8hp7n545m-replit_rtld_loader-1/rtld_loader.so}"
  else
    export LD_LIBRARY_PATH="\${REPLIT_LD_LIBRARY_PATH}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
  fi
fi

# Strategy 0: PATH lookup
if command -v node >/dev/null 2>&1; then
  NODE_BIN=\$(command -v node)
  echo "[run-api] node (PATH): \$NODE_BIN" >&2
  exec "\$NODE_BIN" "\$ENTRY"
fi

# Strategy 1: Known paths from build time and fallbacks
for NODE_PATH in \\
  "${ACTUAL_NODE}" \\
  "${WRAPPER_NODE}" \\
  "/nix/store/9cyx2v23dip6p9q98384k9v06c96qskb-nodejs-24.13.0/bin/node" \\
  "/nix/store/s7awkfc4pym4zj139fsxrjs5xwf5hhnd-nodejs-24.13.0-wrapped/bin/node" \\
  "/usr/local/bin/node" \\
  "/usr/bin/node"; do
  if [ -x "\$NODE_PATH" ]; then
    echo "[run-api] node (known): \$NODE_PATH" >&2
    exec "\$NODE_PATH" "\$ENTRY"
  fi
done

# Strategy 2: Glob (avoids slow ls /nix/store/)
for GLOB_PATH in /nix/store/*nodejs*24*/bin/node /nix/store/*nodejs*/bin/node; do
  if [ -x "\$GLOB_PATH" ]; then
    echo "[run-api] node (glob): \$GLOB_PATH" >&2
    exec "\$GLOB_PATH" "\$ENTRY"
  fi
done

echo "[run-api] ERROR: no executable node binary found" >&2
echo "[run-api] REPLIT_LD_LIBRARY_PATH=\${REPLIT_LD_LIBRARY_PATH:-unset}" >&2
echo "[run-api] REPLIT_RTLD_LOADER=\${REPLIT_RTLD_LOADER:-unset}" >&2
echo "[run-api] REPLIT_NIX_CHANNEL=\${REPLIT_NIX_CHANNEL:-unset}" >&2
echo "[run-api] LD_AUDIT=\${LD_AUDIT:-unset}" >&2
echo "[run-api] PATH=\$PATH" >&2
exit 127
LAUNCHER_EOF

chmod +x run-api.sh
echo "[build-frontend] run-api.sh ready"
echo "[build-frontend] --- generated run-api.sh ---"
cat run-api.sh
echo "[build-frontend] --- end run-api.sh ---"
