/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as ThinkFreelyRouteImport } from './routes/think-freely'
import { Route as ProjectCompassRouteImport } from './routes/project-compass'
import { Route as ParkingLotRouteImport } from './routes/parking-lot'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as GuardReportRouteImport } from './routes/guard-report'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkFreelyRoute = ThinkFreelyRouteImport.update({
  id: '/think-freely',
  path: '/think-freely',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectCompassRoute = ProjectCompassRouteImport.update({
  id: '/project-compass',
  path: '/project-compass',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingLotRoute = ParkingLotRouteImport.update({
  id: '/parking-lot',
  path: '/parking-lot',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardReportRoute = GuardReportRouteImport.update({
  id: '/guard-report',
  path: '/guard-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/guard-report': typeof GuardReportRoute
  '/ledger': typeof LedgerRoute
  '/parking-lot': typeof ParkingLotRoute
  '/project-compass': typeof ProjectCompassRoute
  '/think-freely': typeof ThinkFreelyRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/guard-report': typeof GuardReportRoute
  '/ledger': typeof LedgerRoute
  '/parking-lot': typeof ParkingLotRoute
  '/project-compass': typeof ProjectCompassRoute
  '/think-freely': typeof ThinkFreelyRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/guard-report': typeof GuardReportRoute
  '/ledger': typeof LedgerRoute
  '/parking-lot': typeof ParkingLotRoute
  '/project-compass': typeof ProjectCompassRoute
  '/think-freely': typeof ThinkFreelyRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/guard-report'
    | '/ledger'
    | '/parking-lot'
    | '/project-compass'
    | '/think-freely'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/guard-report'
    | '/ledger'
    | '/parking-lot'
    | '/project-compass'
    | '/think-freely'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/guard-report'
    | '/ledger'
    | '/parking-lot'
    | '/project-compass'
    | '/think-freely'
    | '/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  GuardReportRoute: typeof GuardReportRoute
  LedgerRoute: typeof LedgerRoute
  ParkingLotRoute: typeof ParkingLotRoute
  ProjectCompassRoute: typeof ProjectCompassRoute
  ThinkFreelyRoute: typeof ThinkFreelyRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/think-freely': {
      id: '/think-freely'
      path: '/think-freely'
      fullPath: '/think-freely'
      preLoaderRoute: typeof ThinkFreelyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-compass': {
      id: '/project-compass'
      path: '/project-compass'
      fullPath: '/project-compass'
      preLoaderRoute: typeof ProjectCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking-lot': {
      id: '/parking-lot'
      path: '/parking-lot'
      fullPath: '/parking-lot'
      preLoaderRoute: typeof ParkingLotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard-report': {
      id: '/guard-report'
      path: '/guard-report'
      fullPath: '/guard-report'
      preLoaderRoute: typeof GuardReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  GuardReportRoute: GuardReportRoute,
  LedgerRoute: LedgerRoute,
  ParkingLotRoute: ParkingLotRoute,
  ProjectCompassRoute: ProjectCompassRoute,
  ThinkFreelyRoute: ThinkFreelyRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
